export const RESOLVED_LOCATION_REPO = Symbol('RESOLVED_LOCATION_REPO');
export const PROVIDE_LOCATION_ENTITY = Symbol('PROVIDE_LOCATION_ENTITY');
export const WMS_MODULE_OPTIONS = Symbol('WMS_MODULE_OPTIONS');
