export const RESOLVED_TREE_LOCATION_REPO = Symbol('RESOLVED_TREE_LOCATION_REPO');
export const PROVIDE_LOCATION_ENTITY = Symbol('PROVIDE_LOCATION_ENTITY');
export const WMS_MODULE_OPTIONS = Symbol('WMS_MODULE_OPTIONS');

export const RESOLVED_MATERIAL_REPO = Symbol('RESOLVED_MATERIAL_REPO');
export const PROVIDE_MATERIAL_ENTITY = Symbol('PROVIDE_MATERIAL_ENTITY');

export const RESOLVED_BATCH_REPO = Symbol('RESOLVED_BATCH_REPO');
export const PROVIDE_BATCH_ENTITY = Symbol('PROVIDE_BATCH_ENTITY');

export const RESOLVED_ORDER_REPO = Symbol('RESOLVED_ORDER_REPO');
export const PROVIDE_ORDER_ENTITY = Symbol('PROVIDE_ORDER_ENTITY');
