import { getMetadataArgsStorage } from 'typeorm';
import '../src/oidc/models/oidc-client.entity';
import '../src/oidc/models/oidc-payload.entity';

interface ColumnShape {
  readonly type: unknown;
  readonly length: string | number | undefined;
}

const columnsOf = (table: string): Record<string, ColumnShape> => {
  const storage = getMetadataArgsStorage();
  const target = storage.tables.find(candidate => candidate.name === table)?.target;

  if (!target) throw new Error(`No entity registered for ${table}`);

  return Object.fromEntries(
    storage.columns
      .filter(column => column.target === target)
      .map(column => [column.propertyName, { type: column.options.type, length: column.options.length }]),
  );
};

/**
 * A bound on a column is a decision, not a default, so each one is asserted
 * either way. The rule: bounded when this package or a spec decides the value,
 * unbounded when the application does.
 */
describe('oidc entity schema', () => {
  describe('oidc_clients', () => {
    const columns = (): Record<string, ColumnShape> => columnsOf('oidc_clients');

    it.each(['clientSecret', 'name', 'scope'])('should leave %s unbounded', property => {
      const column = columns()[property];

      expect(column.type).toBe('text');
      expect(column.length).toBeUndefined();
    });

    it('should keep the primary key bounded, because a btree key cannot be unbounded', () => {
      expect(columns().clientId).toEqual({ type: 'varchar', length: 255 });
    });

    it('should keep tokenEndpointAuthMethod bounded, since the specs fix its values', () => {
      expect(columns().tokenEndpointAuthMethod).toEqual({ type: 'varchar', length: 64 });
    });
  });

  describe('oidc_payloads', () => {
    // Every one of these is generated by oidc-provider, not supplied by an
    // application, so their lengths are known and bounding them is free.
    it.each([
      ['model', 64],
      ['id', 255],
      ['grantId', 255],
      ['userCode', 255],
      ['uid', 255],
    ])('should keep %s bounded', (property, length) => {
      expect(columnsOf('oidc_payloads')[property]).toEqual({ type: 'varchar', length });
    });

    it('should store the payload as jsonb', () => {
      expect(columnsOf('oidc_payloads').payload.type).toBe('jsonb');
    });
  });
});
