import {
  MEMBER_BASE_MODULE_OPTIONS,
  LOGIN_FAILED_BAN_THRESHOLD,
  RESET_PASSWORD_TOKEN_EXPIRATION,
  RESET_PASSWORD_TOKEN_SECRET,
  CASBIN_ENFORCER,
  CASBIN_PERMISSION_DECORATOR,
  CASBIN_PERMISSION_CHECKER,
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_EXPIRATION,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRATION,
  ENABLE_GLOBAL_GUARD,
  ONLY_RESET_REFRESH_TOKEN_EXPIRATION_BY_PASSWORD,
  COOKIE_MODE,
  LOGIN_FAILED_AUTO_UNLOCK_SECONDS,
  ACCESS_TOKEN_COOKIE_NAME,
  REFRESH_TOKEN_COOKIE_NAME,
  PROVIDE_MEMBER_ENTITY,
  RESOLVED_MEMBER_REPO,
  PASSWORD_SHOULD_INCLUDE_UPPERCASE,
  PASSWORD_SHOULD_INCLUDE_LOWERCASE,
  PASSWORD_SHOULD_INCLUDE_DIGIT,
  PASSWORD_SHOULD_INCLUDE_SPECIAL_CHARACTER,
  PASSWORD_MIN_LENGTH,
  PASSWORD_POLICY_REGEXP,
  PASSWORD_HISTORY_LIMIT,
  PASSWORD_AGE_LIMIT_IN_DAYS,
  FORCE_REJECT_LOGIN_ON_PASSWORD_EXPIRED,
  CUSTOMIZED_JWT_PAYLOAD,
  OAUTH2_PROVIDERS,
  OAUTH2_CLIENT_DEST_URL,
} from '../src/typings/member-base.tokens';

describe('Member Base Tokens', () => {
  const tokens = [
    { name: 'MEMBER_BASE_MODULE_OPTIONS', token: MEMBER_BASE_MODULE_OPTIONS },
    { name: 'LOGIN_FAILED_BAN_THRESHOLD', token: LOGIN_FAILED_BAN_THRESHOLD },
    { name: 'RESET_PASSWORD_TOKEN_EXPIRATION', token: RESET_PASSWORD_TOKEN_EXPIRATION },
    { name: 'RESET_PASSWORD_TOKEN_SECRET', token: RESET_PASSWORD_TOKEN_SECRET },
    { name: 'CASBIN_ENFORCER', token: CASBIN_ENFORCER },
    { name: 'CASBIN_PERMISSION_DECORATOR', token: CASBIN_PERMISSION_DECORATOR },
    { name: 'CASBIN_PERMISSION_CHECKER', token: CASBIN_PERMISSION_CHECKER },
    { name: 'ACCESS_TOKEN_SECRET', token: ACCESS_TOKEN_SECRET },
    { name: 'ACCESS_TOKEN_EXPIRATION', token: ACCESS_TOKEN_EXPIRATION },
    { name: 'REFRESH_TOKEN_SECRET', token: REFRESH_TOKEN_SECRET },
    { name: 'REFRESH_TOKEN_EXPIRATION', token: REFRESH_TOKEN_EXPIRATION },
    { name: 'ENABLE_GLOBAL_GUARD', token: ENABLE_GLOBAL_GUARD },
    { name: 'ONLY_RESET_REFRESH_TOKEN_EXPIRATION_BY_PASSWORD', token: ONLY_RESET_REFRESH_TOKEN_EXPIRATION_BY_PASSWORD },
    { name: 'COOKIE_MODE', token: COOKIE_MODE },
    { name: 'LOGIN_FAILED_AUTO_UNLOCK_SECONDS', token: LOGIN_FAILED_AUTO_UNLOCK_SECONDS },
    { name: 'ACCESS_TOKEN_COOKIE_NAME', token: ACCESS_TOKEN_COOKIE_NAME },
    { name: 'REFRESH_TOKEN_COOKIE_NAME', token: REFRESH_TOKEN_COOKIE_NAME },
    { name: 'PROVIDE_MEMBER_ENTITY', token: PROVIDE_MEMBER_ENTITY },
    { name: 'RESOLVED_MEMBER_REPO', token: RESOLVED_MEMBER_REPO },
    { name: 'PASSWORD_SHOULD_INCLUDE_UPPERCASE', token: PASSWORD_SHOULD_INCLUDE_UPPERCASE },
    { name: 'PASSWORD_SHOULD_INCLUDE_LOWERCASE', token: PASSWORD_SHOULD_INCLUDE_LOWERCASE },
    { name: 'PASSWORD_SHOULD_INCLUDE_DIGIT', token: PASSWORD_SHOULD_INCLUDE_DIGIT },
    { name: 'PASSWORD_SHOULD_INCLUDE_SPECIAL_CHARACTER', token: PASSWORD_SHOULD_INCLUDE_SPECIAL_CHARACTER },
    { name: 'PASSWORD_MIN_LENGTH', token: PASSWORD_MIN_LENGTH },
    { name: 'PASSWORD_POLICY_REGEXP', token: PASSWORD_POLICY_REGEXP },
    { name: 'PASSWORD_HISTORY_LIMIT', token: PASSWORD_HISTORY_LIMIT },
    { name: 'PASSWORD_AGE_LIMIT_IN_DAYS', token: PASSWORD_AGE_LIMIT_IN_DAYS },
    { name: 'FORCE_REJECT_LOGIN_ON_PASSWORD_EXPIRED', token: FORCE_REJECT_LOGIN_ON_PASSWORD_EXPIRED },
    { name: 'CUSTOMIZED_JWT_PAYLOAD', token: CUSTOMIZED_JWT_PAYLOAD },
    { name: 'OAUTH2_PROVIDERS', token: OAUTH2_PROVIDERS },
    { name: 'OAUTH2_CLIENT_DEST_URL', token: OAUTH2_CLIENT_DEST_URL },
  ];

  it('should export all tokens as symbols', () => {
    tokens.forEach(({ token }) => {
      expect(typeof token).toBe('symbol');
    });
  });

  it('should have unique tokens', () => {
    const tokenSet = new Set(tokens.map(({ token }) => token));

    expect(tokenSet.size).toBe(tokens.length);
  });

  it.each(tokens)('$name should have correct symbol description', ({ name, token }) => {
    expect(token.toString()).toBe(`Symbol(${name})`);
  });
});
