import {
  InvalidPasswordError,
  InvalidToken,
  MemberAlreadyExistedError,
  MemberBannedError,
  MemberNotFoundError,
  PasswordChangedError,
  PasswordDoesNotMeetPolicyError,
  PasswordExpiredError,
  PasswordShouldUpdatePasswordError,
  PasswordValidationError,
  RefreshTokenReuseDetectedError,
  SessionExpiredError,
  SessionNotFoundError,
  SessionRevokedError,
  SessionRotationConflictError,
} from './base.error';

export const Errors = {
  MemberNotFoundError,
  PasswordDoesNotMeetPolicyError,
  InvalidPasswordError,
  PasswordValidationError,
  InvalidToken,
  MemberAlreadyExistedError,
  PasswordChangedError,
  MemberBannedError,
  PasswordExpiredError,
  PasswordShouldUpdatePasswordError,
  SessionRevokedError,
  SessionExpiredError,
  RefreshTokenReuseDetectedError,
  SessionNotFoundError,
  SessionRotationConflictError,
};
