export const LOGIN_FAILED_BAN_THRESHOLD = Symbol('LOGIN_FAILED_BAN_THRESHOLD');
export const RESET_PASSWORD_TOKEN_EXPIRATION = Symbol(
  'RESET_PASSWORD_TOKEN_EXPIRATION',
);
export const RESET_PASSWORD_TOKEN_SECRET = Symbol(
  'RESET_PASSWORD_TOKEN_SECRET',
);
