export const MEMBER_BASE_MODULE_OPTIONS = Symbol('MEMBER_BASE_MODULE_OPTIONS');
export const LOGIN_FAILED_BAN_THRESHOLD = Symbol('LOGIN_FAILED_BAN_THRESHOLD');
export const RESET_PASSWORD_TOKEN_EXPIRATION = Symbol(
  'RESET_PASSWORD_TOKEN_EXPIRATION',
);
export const RESET_PASSWORD_TOKEN_SECRET = Symbol(
  'RESET_PASSWORD_TOKEN_SECRET',
);

export const CASBIN_ENFORCER = Symbol('CASBIN_ENFORCER');

// Options Entity Providers
export const PROVIDE_MEMBER_ENTITY = Symbol('PROVIDE_MEMBER_ENTITY');

// Resolved Entity Repository Providers
export const RESOLVED_MEMBER_REPO = Symbol('RESOLVED_MEMBER_REPO');
