import type { TypeORMAdapterOptions } from 'typeorm-adapter';
import type { BaseMemberEntity } from '../models/base-member.entity';
import type { ReflectableDecorator } from '@nestjs/core';
import type { OAuth2Provider } from './oauth2-provider.interface';
import type {
  AuthenticationProvider,
  AutoProvisionStrategy,
  IdentitySyncHandler,
  LinkExistingAccountStrategy,
} from './authentication-provider.interface';
import type {
  CasbinDomainResolver,
  CasbinPermissionCheckerParams,
  CasbinPermissionCheckerResult,
} from './casbin-permission';

export interface MemberBaseModuleOptionsDTO<
  MemberEntity extends BaseMemberEntity = BaseMemberEntity,
  TokenPayload extends {
    id: string;
    account?: string;
    domain?: string;
  } = Pick<MemberEntity, 'id' | 'account'> & {
    domain?: string;
  },
> {
  loginFailedBanThreshold?: number; // default: 5
  resetPasswordTokenExpiration?: number; // default: 60 * 60 * 1 = 1 hour
  resetPasswordTokenSecret?: string; // default: random string generated by crypto.randomBytes(16).toString('hex')
  cookieMode?: boolean; // default: false, if true, will use cookie instead of header for token, cookie name: 'token'
  loginFailedAutoUnlockSeconds?: number; // default: null, if set, will enable auto unlock after the specified seconds

  // Tokens
  accessTokenSecret?: string; // default: random string generated by crypto.randomBytes(16).toString('hex')
  accessTokenExpiration?: number; // default: 60 * 15, 15 minutes
  refreshTokenSecret?: string; // default: random string generated by crypto.randomBytes(16).toString('hex')
  refreshTokenExpiration?: number; // default: 60 * 60 * 24 * 90, 90 days
  onlyResetRefreshTokenExpirationByPassword?: boolean; // default: false, if true, will only reset refresh token expiration when password is changed

  // Casbin
  enableGlobalGuard?: boolean; // default: true
  casbinAdapterOptions?: TypeORMAdapterOptions;
  casbinModelString?: string; // default: RBAC with domains
  casbinPermissionDecorator?: ReflectableDecorator<[string, string][]>;
  casbinPermissionChecker?: (params: CasbinPermissionCheckerParams<TokenPayload>) => CasbinPermissionCheckerResult;
  casbinDomainResolver?: CasbinDomainResolver<TokenPayload>; // default: undefined, only affects the default checker

  // Entities
  memberEntity?: new () => MemberEntity; // default: MemberEntity

  // Password Policy
  passwordShouldIncludeUppercase?: boolean; // default: true
  passwordShouldIncludeLowercase?: boolean; // default: true
  passwordShouldIncludeDigit?: boolean; // default: true
  passwordShouldIncludeSpecialCharacters?: boolean; // default: false
  passwordMinLength?: number; // default: 8
  passwordPolicyRegExp?: RegExp; // default: undefined, if set, will override the above options
  passwordHistoryLimit?: number; // default undefined, if set, will enable password history check
  passwordAgeLimitInDays?: number; // default undefined, if set, will enable password age check
  forceRejectLoginOnPasswordExpired?: boolean; // default: false, if true, will reject login when password is expired
  customizedJwtPayload?: (member: MemberEntity) => TokenPayload; // default: undefined

  // OAuth2
  oauth2Providers?: OAuth2Provider[];
  oauth2ClientDestUrl?: string; // default: '/login'

  // Authentication Gateway
  /**
   * Extra authentication sources registered alongside the built-in
   * account/password provider (an LDAP directory, an upstream OIDC issuer...).
   * The password provider is always present and cannot be removed.
   */
  authProviders?: AuthenticationProvider[];
  /**
   * What to do when an external identity has no local member yet.
   * default: true — provision a passwordless member on first login.
   * Pass false to reject unknown identities, or a function to decide per
   * identity (a directory group check, an approval workflow).
   */
  autoProvision?: AutoProvisionStrategy;
  /**
   * Whether an unbound external identity may claim an existing local member
   * whose account equals the identifier.
   * default: true — matches the behaviour the OAuth2 flows always had.
   * Set 'verified-only' to require the provider to have verified the
   * identifier, or false to disable linking. A warning is emitted on boot and
   * on every actual takeover while linking is enabled.
   */
  linkExistingAccount?: LinkExistingAccountStrategy;
  /**
   * Write directory attributes back to the member after an external identity
   * resolves.
   * default: undefined — nothing is written, because a write per login and the
   * choice of which fields a directory may overwrite are the application's
   * decisions, not this module's.
   */
  syncOnAuthenticate?: IdentitySyncHandler<MemberEntity>;

  // Default Admin
  defaultAdminAccount?: string; // default: undefined, if set, will auto-create this account with super-admin permissions on startup
  defaultAdminPassword?: string; // default: undefined, if omitted (and defaultAdminAccount set), a policy-compliant random password is generated and logged once
}

// Non-breaking alias with community-preferred naming
export type MemberBaseModuleOptions<
  MemberEntity extends BaseMemberEntity = BaseMemberEntity,
  TokenPayload extends {
    id: string;
    account?: string;
    domain?: string;
  } = Pick<MemberEntity, 'id' | 'account'> & {
    domain?: string;
  },
> = MemberBaseModuleOptionsDTO<MemberEntity, TokenPayload>;
