import type { TypeORMAdapterOptions } from 'typeorm-adapter';
import type { BaseMemberEntity } from '../models/base-member.entity';
import type { ReflectableDecorator } from '@nestjs/core';
import type { OAuth2Provider } from './oauth2-provider.interface';
import type {
  AuthenticationProvider,
  AutoProvisionStrategy,
  IdentitySyncHandler,
  LinkExistingAccountStrategy,
} from './authentication-provider.interface';
import type {
  CasbinDomainResolver,
  CasbinPermissionCheckerParams,
  CasbinPermissionCheckerResult,
} from './casbin-permission';
import type { CasbinRuleEntity } from './casbin-rule-entity';
import type { PasswordHashOptions } from './password-hash-options';
import type { RedirectAuthOptions } from './redirect-auth.options';

export interface MemberBaseModuleOptionsDTO<
  MemberEntity extends BaseMemberEntity = BaseMemberEntity,
  TokenPayload extends {
    id: string;
    account?: string;
    domain?: string;
  } = Pick<MemberEntity, 'id' | 'account'> & {
    domain?: string;
  },
> {
  loginFailedBanThreshold?: number; // default: 5
  resetPasswordTokenExpiration?: number; // default: 60 * 60 * 1 = 1 hour
  resetPasswordTokenSecret?: string; // default: random string generated by crypto.randomBytes(16).toString('hex')
  cookieMode?: boolean; // default: false, if true, will use cookie instead of header for token
  loginFailedAutoUnlockSeconds?: number; // default: null, if set, will enable auto unlock after the specified seconds

  // Cookies (cookieMode only). Every attribute adapts to the request when left unset.
  accessTokenCookieName?: string; // default: 'access_token'
  refreshTokenCookieName?: string; // default: 'refresh_token'
  cookiePath?: string; // default: '/', so one cookie serves every route
  cookieSameSite?: 'lax' | 'strict' | 'none'; // default: 'lax'
  /**
   * default: true, except on localhost / 127.0.0.1 / ::1, where a Secure cookie
   * would never be stored over plain http and local development would break.
   */
  cookieSecure?: boolean;
  /**
   * Domain attribute.
   *
   * default: absent, which scopes the cookie to exactly the host that served
   * the response. Set it — `.example.com` — only when sibling subdomains are
   * meant to share the session, since every one of them can then read it.
   */
  cookieDomain?: string;

  // Tokens
  accessTokenSecret?: string; // default: random string generated by crypto.randomBytes(16).toString('hex')
  accessTokenExpiration?: number; // default: 60 * 15, 15 minutes
  refreshTokenSecret?: string; // default: random string generated by crypto.randomBytes(16).toString('hex')
  refreshTokenExpiration?: number; // default: 60 * 60 * 24 * 90, 90 days
  onlyResetRefreshTokenExpirationByPassword?: boolean; // default: false, if true, will only reset refresh token expiration when password is changed

  // Casbin
  enableGlobalGuard?: boolean; // default: true
  /**
   * The role treated as allow-all by the default permission checker, and the
   * domain that grouping is keyed to.
   *
   * default: SUPER_ADMIN_ROLE ('::SUPER_ADMIN::') and DEFAULT_CASBIN_DOMAIN
   * ('::DEFAULT::'). Change them only when an existing policy table already
   * uses those strings for something else — every grouping policy written by
   * an earlier configuration keeps the name it was written with.
   */
  superAdminRole?: string;
  defaultCasbinDomain?: string;
  casbinAdapterOptions?: TypeORMAdapterOptions;
  /**
   * Entity backing the Casbin policy table.
   *
   * default: typeorm-adapter's own `CasbinRule`, which is mapped to `casbin_rule`.
   * Subclass it with `@Entity('another_table')` when two applications share one
   * database and must not overwrite each other's policies — the table name is
   * the only axis of separation that does not also require a separate schema.
   *
   * With `casbinAdapterOptions: { connection }` typeorm-adapter does not build
   * its own entity list, so register this entity on that DataSource too.
   */
  casbinRuleEntity?: CasbinRuleEntity;
  casbinModelString?: string; // default: RBAC with domains
  casbinPermissionDecorator?: ReflectableDecorator<[string, string][]>;
  casbinPermissionChecker?: (params: CasbinPermissionCheckerParams<TokenPayload>) => CasbinPermissionCheckerResult;
  casbinDomainResolver?: CasbinDomainResolver<TokenPayload>; // default: undefined, only affects the default checker

  // Entities
  memberEntity?: new () => MemberEntity; // default: MemberEntity

  // Password Policy
  passwordShouldIncludeUppercase?: boolean; // default: true
  passwordShouldIncludeLowercase?: boolean; // default: true
  passwordShouldIncludeDigit?: boolean; // default: true
  passwordShouldIncludeSpecialCharacters?: boolean; // default: false
  passwordMinLength?: number; // default: 8
  passwordPolicyRegExp?: RegExp; // default: undefined, if set, will override the above options
  passwordHistoryLimit?: number; // default undefined, if set, will enable password history check
  passwordAgeLimitInDays?: number; // default undefined, if set, will enable password age check
  forceRejectLoginOnPasswordExpired?: boolean; // default: false, if true, will reject login when password is expired
  customizedJwtPayload?: (member: MemberEntity) => TokenPayload; // default: undefined
  /**
   * argon2 cost parameters used for every password this module hashes.
   * default: argon2's own defaults — the right cost depends on the hardware,
   * which this package cannot know. Raising it does not invalidate existing
   * hashes; argon2 reads each hash's parameters from the hash itself.
   */
  passwordHashOptions?: PasswordHashOptions;

  // Login Log
  /**
   * Record an attempt in member_login_logs on every login.
   * default: true
   */
  loginLogEnabled?: boolean;
  /**
   * Store the caller's IP with that record.
   * default: true. Set false to keep logging attempts without retaining an
   * address, which is often what a data-retention policy actually asks for.
   */
  loginLogRecordIp?: boolean;

  // Redirect login routes
  /**
   * Mount `GET /:prefix/:channel/start` and `GET /:prefix/:channel/callback`
   * for the `kind: 'redirect'` providers registered in `authProviders`.
   *
   * default: undefined — no route is registered. Whether an endpoint exists,
   * where it is mounted and who may reach it is the host application's
   * decision, the same call 0.8.0 made when `OidcAdminController` was
   * withdrawn. Supplying the object (even empty) is the opt-in.
   *
   * `OAuth2Provider` channels are unaffected and keep using
   * `OAuthCallbacksController`.
   */
  redirectAuth?: RedirectAuthOptions;

  // OAuth2
  oauth2Providers?: OAuth2Provider[];
  oauth2ClientDestUrl?: string; // default: '/login'

  // Authentication Gateway
  /**
   * Extra authentication sources registered alongside the built-in
   * account/password provider (an LDAP directory, an upstream OIDC issuer...).
   * The password provider is always present and cannot be removed.
   */
  authProviders?: AuthenticationProvider[];
  /**
   * What to do when an external identity has no local member yet.
   * default: true — provision a passwordless member on first login.
   * Pass false to reject unknown identities, or a function to decide per
   * identity (a directory group check, an approval workflow).
   */
  autoProvision?: AutoProvisionStrategy;
  /**
   * Whether an unbound external identity may claim an existing local member
   * whose account equals the identifier.
   * default: true — matches the behaviour the OAuth2 flows always had.
   * Set 'verified-only' to require the provider to have verified the
   * identifier, or false to disable linking. A warning is emitted on boot and
   * on every actual takeover while linking is enabled.
   */
  linkExistingAccount?: LinkExistingAccountStrategy;
  /**
   * Write directory attributes back to the member after an external identity
   * resolves.
   * default: undefined — nothing is written, because a write per login and the
   * choice of which fields a directory may overwrite are the application's
   * decisions, not this module's.
   */
  syncOnAuthenticate?: IdentitySyncHandler<MemberEntity>;

  // Default Admin
  defaultAdminAccount?: string; // default: undefined, if set, will auto-create this account with super-admin permissions on startup
  defaultAdminPassword?: string; // default: undefined, if omitted (and defaultAdminAccount set), a policy-compliant random password is generated and logged once
}

// Non-breaking alias with community-preferred naming
export type MemberBaseModuleOptions<
  MemberEntity extends BaseMemberEntity = BaseMemberEntity,
  TokenPayload extends {
    id: string;
    account?: string;
    domain?: string;
  } = Pick<MemberEntity, 'id' | 'account'> & {
    domain?: string;
  },
> = MemberBaseModuleOptionsDTO<MemberEntity, TokenPayload>;
