import { BaseMemberEntity } from '../models';

export interface MemberBaseRootModuleOptionsDto<BM extends BaseMemberEntity> {
  loginFailedBanThreshold?: number; // default: 5
  resetPasswordTokenExpiration?: number; // default: 60 * 60 * 1 = 1 hour
  resetPasswordTokenSecret?: string; // default: random string generated by crypto.randomBytes(16).toString('hex')
  memberEntity?: new () => BM; // default: MemberEntity
}
