export const CMS_BASE_GRAPHQL_MODULE_OPTIONS = Symbol(
  'CMS_BASE_GRAPHQL_MODULE_OPTIONS',
);
export const MAP_ARTICLE_CUSTOM_FIELDS_TO_ENTITY_COLUMNS = Symbol(
  'MAP_ARTICLE_CUSTOM_FIELDS_TO_ENTITY_COLUMNS',
);
export const MAP_CATEGORY_CUSTOM_FIELDS_TO_ENTITY_COLUMNS = Symbol(
  'MAP_CATEGORY_CUSTOM_FIELDS_TO_ENTITY_COLUMNS',
);
