name: Rytass Utils CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js with Yarn Cache
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - run: yarn
      - run: yarn test
